build-p4:
    name: ESP-IDF Build (T-Display P4)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: build
        uses: espressif/idf-build-action@v1
        with:
          conf_file: sdkconfig
          idf_version: v5.3
          target: esp32p4

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: trail-mate-t-display-p4-amoled
          path: build/trail-mate.bin
